### ISSUE TITLE
HTTPS Repo needed

### ISSUE THREAD

**Issue by adamretter** [indexdata/cql-java#11]
The latest version of Maven 3.8.1 does not play-well with Maven repos that are non-https.

It seems that cql-java is published here http://maven.indexdata.com/ and that https://maven.indexdata.com/ is inaccessible. Please consider enabling HTTPS or publishing to Maven Central.

**Comment by dltj** [comment]
Thank you for the report, Adam...I will put this on our devops backlog.

**Comment by dltj** [comment]
Fixed now.  Please confirm that you can reach https://maven.indexdata.com/ and re-open this issue if needed.  Thanks again for the report.

**Comment by adamretter** [comment]
@dltj That works now, thanks :-)
