### ISSUE TITLE
Got CQLParseException when pass cql schema

### ISSUE THREAD

**Issue by pioardi** [indexdata/cql-java#8]
Hello ,
what I need is a parser that starting from DDL (create, alter tables and other instructions) will get info about the schema into a java object.

Trying to use this library I'm getting CQLParseException:

 Error parsing cql schema org.z3950.zing.cql.CQLParseException: expected boolean, got '('

 Error parsing cql schema org.z3950.zing.cql.CQLParseException: expected index or term, got EOF

This library is suitable for this type of thing?
Thanks in advance

**Comment by MikeTaylor** [comment]
No. CQL is nothing to do with SQL. You need something completely different.
